# MUS 201 assignment 6

In [1]:
import numpy as np
from miditoolkit.midi import parser

pitch_class_to_note = ['C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B']
n_semitones = 12

## Question 1

The tone-row used in Alban Berg's Violin Concerto is:

![](https://i.imgur.com/8VIw7iZ.png)

Write this tone-row using:
 - letter notation
 - numbers

In [2]:
pitches = [note.pitch for note in parser.MidiFile('tone_row.mid').instruments[0].notes]
tone_row = np.array([(pitch - pitches[0]) % n_semitones for pitch in pitches])

print(f'tone-row = {[pitch_class_to_note[pitch % n_semitones] for pitch in pitches]}')
print(f'tone-row = {tone_row.__repr__()}')

tone-row = ['G', 'Bb', 'D', 'F#', 'A', 'C', 'E', 'Ab', 'B', 'C#', 'Eb', 'F']
tone-row = array([ 0,  3,  7, 11,  2,  5,  9,  1,  4,  6,  8, 10])


## Question 2

Write the matrix for this tone-row.

In [3]:
matrix = np.full((n_semitones, n_semitones), 0)
for i, tone in enumerate(tone_row):
    matrix[i, :] = (tone_row + n_semitones - tone) % n_semitones
print(matrix)

[[ 0  3  7 11  2  5  9  1  4  6  8 10]
 [ 9  0  4  8 11  2  6 10  1  3  5  7]
 [ 5  8  0  4  7 10  2  6  9 11  1  3]
 [ 1  4  8  0  3  6 10  2  5  7  9 11]
 [10  1  5  9  0  3  7 11  2  4  6  8]
 [ 7 10  2  6  9  0  4  8 11  1  3  5]
 [ 3  6 10  2  5  8  0  4  7  9 11  1]
 [11  2  6 10  1  4  8  0  3  5  7  9]
 [ 8 11  3  7 10  1  5  9  0  2  4  6]
 [ 6  9  1  5  8 11  3  7 10  0  2  4]
 [ 4  7 11  3  6  9  1  5  8 10  0  2]
 [ 2  5  9  1  4  7 11  3  6  8 10  0]]


## Question 3

Using musical notation, write the RI10 of the tone-row.

In [4]:
print([pitch_class_to_note[(pitches[0] + pitch_class) % 12] for pitch_class in np.flip(matrix[:, 11])])

['G', 'A', 'B', 'C#', 'E', 'Ab', 'C', 'Eb', 'F#', 'Bb', 'D', 'F']


## Question 4

Briefly describe Berg's reasons for creating this particular tone-row.

By outlining triads in the first few notes, the music based on this tone row can sound a bit tonal even though it isn't.

## Question 5

How is this tone-row different from the one used by Schoenberg in Variations for Orchestra?

While Berg manipulates the overall sounding of the pieces with his row, Schoenberg uses his row more as a motif or melody.