# MUS 201 Final Test

 - Semester: Fall 2020
 - Name: Joshua Chang
 - NetID: chchang6

All Python code are written myself except the NumPy library, which I explicitly imported for matrix and logarithmic calculations. This and other code works from MUS 201 will be on GitHub after the semester ends.

In [1]:
import numpy as np
from frequency import Frequency

n_semitones = 12

## Question 1

Define five out of the eight following terms. For each of them give at least one example of composer and work that can be connected to the term.

1. additive synthesis
     - As the name suggests, **additive synthesis** is as simple as adding sound waves together to get a desired sound. In often cases, sine waves are used since this is the most common type of oscillation in the nature.
     - Example: *A.N.L -folds* by Sever Tipei


2. klangfarbenmelodie
     - **Klangfarbenmelodie** is a technique that distributes a musical line to multiple instruments (often alternately) with a view to enrich such musical line's timbre.
     - Example: *Concerto for Nine Instruments* by Anton Webern
     
     
3. non-retrogradable rhythm
     - As the name suggests, **non-retrogradable rhythm** is not retrogradable (duh), meaning the retrograde of the rhythm has to be equivalent to itself, like a pendulum.
     - Example: *Danse de la fureur, pour les sept trompettes* by Olivier Messiaen
     
     
4. fibonacci series of numbers
     - The **fibonacci numbers** can be expressed as a recursive function as such, where f(n) is the nth fibonacci number.
         - f(1) = 1
         - f(2) = 1
         - f(i+2) = f(i) + f(i+1) for all i > 0
     - (continued definition) The fibonacci numbers have a trait that when n approaches infinity, f(n+1)/f(n) is equal to the golden mean.
     - Example: *Danseuses de Delphes* by Claude Debussy
     
     
5. minimalism
     - **Minimalism** is an idea that breaks music down to its fundamentals, with an attempt to minimize things and keep only the essentials.
     - Example: *In C* by Terry Riley.
     
     
6. sound mass
     - **Sound mass** is a musical texture that comprises of dense sounds clusters that are meant to not be intepreted individually, but the overall "cloud" as a whole.
     - Example: *Atmospheres* by Gyorgy Ligeti
     
     
7. musique concrete
     - **Musique concrete** is a type of electronic music (electro-acoustic in particular) that does modifications with pre-recorded sound (not necessarily music).
     - Example: *Concrete PH* by Iannis Xenakis
     
     
8. proportional notation
     - **Proportional notation** is a type of notation that expresses the relative durations physically, meaning that it's proportional to the length of the notes.
     - Example: *Threnody for the Victims of Hiroshima* by Krzysztof Penderecki

## Question 2

Using the following tone-row, use numbers (not pitch names) to find the following forms (building the matrix is optional).

In [2]:
tone_row = np.array([0, 11, 3, 4, 8, 7, 9, 5, 6, 1, 2, 10])

matrix = np.full((n_semitones, n_semitones), 0)
for i, tone in enumerate(tone_row):
    matrix[i, :] = (tone_row + n_semitones - tone) % n_semitones
print(matrix)

[[ 0 11  3  4  8  7  9  5  6  1  2 10]
 [ 1  0  4  5  9  8 10  6  7  2  3 11]
 [ 9  8  0  1  5  4  6  2  3 10 11  7]
 [ 8  7 11  0  4  3  5  1  2  9 10  6]
 [ 4  3  7  8  0 11  1  9 10  5  6  2]
 [ 5  4  8  9  1  0  2 10 11  6  7  3]
 [ 3  2  6  7 11 10  0  8  9  4  5  1]
 [ 7  6 10 11  3  2  4  0  1  8  9  5]
 [ 6  5  9 10  2  1  3 11  0  7  8  4]
 [11 10  2  3  7  6  8  4  5  0  1  9]
 [10  9  1  2  6  5  7  3  4 11  0  8]
 [ 2  1  5  6 10  9 11  7  8  3  4  0]]


In [3]:
print(f' P0 = {matrix[0]}')
print(f' I3 = {matrix[:, 2]}')
print(f' R0 = {np.flip(matrix[0])}')
print(f'RI3 = {np.flip(matrix[:, 2])}')

 P0 = [ 0 11  3  4  8  7  9  5  6  1  2 10]
 I3 = [ 3  4  0 11  7  8  6 10  9  2  1  5]
 R0 = [10  2  1  6  5  9  7  8  4  3 11  0]
RI3 = [ 5  1  2  9 10  6  8  7 11  0  4  3]


## Question 3

Write the first 15 overtones of this sound.

In [4]:
pitch_class_to_note = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B']
Eb2 = Frequency(2, 3)

for i in range(1, 1 + 16):
    overtone = Eb2.nth_overtone(i)
    print(f'note #{i}: {pitch_class_to_note[overtone.pitch_class]}{overtone.octave}')

note #1: Eb2
note #2: Eb3
note #3: Bb3
note #4: Eb4
note #5: G4
note #6: Bb4
note #7: Db5
note #8: Eb5
note #9: F5
note #10: G5
note #11: A5
note #12: Bb5
note #13: B5
note #14: Db6
note #15: D6
note #16: Eb6


![](https://i.imgur.com/TydUhgi.png)

## Question 4

Write a short essay on ONE of the following topics. Mention technical aspects and aesthetics
associated with it. Give at least three examples of works by different composers and refer to materials
from the Reading assignments or class notes.

### Indeterminancy

#### Aesthetics

Indeterminancy is, as its name suggests, a philosophy in music where composers, compared to other musical works, no longer takes 100% control over the details of the music, which makes the music less subjective. There are a few reasons to this.

First of all, the lack of form or structure can be seen as a liberation from the models of composition that existed for thousands of years. The music is less designed, and in a way more geniune to itself rather than to the composer. Such distance between the composer and the work also evokes discussion around the definition meaning of composing and creativity, even music itself.

Speaking of creativity, since indeterminancy on different levels can interrupt the inherent neurophysiological tendencies developed by human composers, the results that are often not predictable to socially-constructed human ear can be in a way more creative-sounding.

#### Types of indeterminancy and notable composers & works

##### Chance music

Chance music is the music with the element of indeterminancy in the composition phase. That is, when the composition is complete, the music does not variate as much on the performance level, at least nowhere near the level of free intepretation like aleatory music.

Chance music are usually music based on certain elements and limitations. Once these two are set, the arrangement of the element that are within the limitations are decided randomly, through means such as coin-flipping, dice-rowing, etc. That being said, the composer can still decide some details, such as the length of the piece or the instrumentation used. The following examples of chance music will also introduce other random techniques.

John Cage is one of the pioneers of chance music, whose most famous piece is probably the *Music of Changes*. The title itself corresponds to the inspiration Cage drew from, the *I Ching*, which in Chinese means "the book of changes." Cage followed the steps of Divination using *I Ching* to create the randomness of the music, and later on used a computer program that models the book along with Lejaren Hiller.

An even more technical way of introducing randomness comes from Iannis Xenakis, who has an engineering background and showcased stochastic distributions in musical composition for the first time. For example, he used the distribution to randomize the attack points of sound so it sounds asymmetrical. One of the works that utilized this technique is *Pithoprakta*.

##### Aleatory music

Aleatory music is the music with the element of indeterminancy in the performance phase. In often cases, the instructions of how to play the music is abstract enough that allows different performers (or performance groups) to determine their methods in various ways.

One common technique of aleatory music is the use of graphic score (though graphic scores are not always aleatory music!). This challenges the convention that musical scores and the music produced are almost like a strict function that is both injective and surjective (or 1-to-1 and onto; those are rather mathematical terms). In aleatory music, rather, according to Karlheinz Stockhausen, are like "universes" where people explore by experiencing more variants of the same piece. Stockhausen's own work *Plus Minus* is an example of a musical score that are more like guidance rather than explicit step-by-step instructions.

However, aleatory music can definitely come in more than in the form of musical scores. In another Stockhausen's composition, *Intensitat*, the instruction comes in the form of text, which says (in English):

```
play single sounds
with such dedication
until you feel the warmth
that radiates from you

play on and sustain it
as long as you can
```

This also blurs the line between the ideas of composer, performer, music, sound, and emotions.